name: Build My Application
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    # Job name is Greeting
    name: Build my App
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Print Current Directory
        run: pwd
      - name: List Files in directory
        run: ls